### PR TITLE
Merge values for default locale and current locale

### PR DESCRIPTION
**Pull request by neonichu**
This creates a behaviour more in line with the delivery API. This seems to be more what people expect.

Example of old behaviour:

```ruby
cat = space.entries.find('nyancat')
puts cat.fields
# {:name=>"Nyan Cat", :likes=>["rainbows", "fish"], :color=>"rainbow", :bestFriend=>{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"happycat"}}, :birthday=>#<DateTime: 2011-04-04T22:00:00+00:00 ((2455656j,79200s,0n),+0s,2299161j)>, :lives=>1337, :image=>{"sys"=>{"type"=>"Link", "linkType"=>"Asset", "id"=>"nyancat"}}}
cat.locale = 'tlh'
puts cat.fields
# {:name=>"Nyan vIghro'", :color=>"yolo"}
```

Example of new behaviour:

```ruby
cat = space.entries.find('nyancat')
puts cat.fields
# {:name=>"Nyan Cat", :likes=>["rainbows", "fish"], :color=>"rainbow", :bestFriend=>{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"happycat"}}, :birthday=>#<DateTime: 2011-04-04T22:00:00+00:00 ((2455656j,79200s,0n),+0s,2299161j)>, :lives=>1337, :image=>{"sys"=>{"type"=>"Link", "linkType"=>"Asset", "id"=>"nyancat"}}}
cat.locale = 'tlh'
puts cat.fields
# {:name=>"Nyan vIghro'", :likes=>["rainbows", "fish"], :color=>"yolo", :bestFriend=>{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"happycat"}}, :birthday=>#<DateTime: 2011-04-04T22:00:00+00:00 ((2455656j,79200s,0n),+0s,2299161j)>, :lives=>1337, :image=>{"sys"=>{"type"=>"Link", "linkType"=>"Asset", "id"=>"nyancat"}}}
```

I'm unsure which one is "better", @pxlpnk @grncdr what do you think?

### CODE REVIEW

**Comment by pxlpnk** [comment]
:+1:

**Comment by pxlpnk** [comment]
Can you add the update to the changelog then we are good to merge this.

**Comment by grncdr** [comment]
In the short term I think this change makes sense.

If breaking backwards compatibility is on the table, I'd really prefer that we remove this weird side-effecting `locale=(code)` method entirely. Instead we should just make locales explicit in the API with an optional parameter to `fields`, so usage would look like:

```rb
cat = space.entries.find('nyancat')
puts cat.fields
# {:name=>"Nyan Cat", :likes=>["rainbows", "fish"], :color=>"rainbow", :bestFriend=>{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"happycat"}}, :birthday=>#<DateTime: 2011-04-04T22:00:00+00:00 ((2455656j,79200s,0n),+0s,2299161j)>, :lives=>1337, :image=>{"sys"=>{"type"=>"Link", "linkType"=>"Asset", "id"=>"nyancat"}}}

puts cat.fields('tlh')
# {:name=>"Nyan vIghro'", :likes=>["rainbows", "fish"], :color=>"yolo", :bestFriend=>{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"happycat"}}, :birthday=>#<DateTime: 2011-04-04T22:00:00+00:00 ((2455656j,79200s,0n),+0s,2299161j)>, :lives=>1337, :image=>{"sys"=>{"type"=>"Link", "linkType"=>"Asset", "id"=>"nyancat"}}}

puts cat.fields('tlh', default_locale: false)
# {:name=>"Nyan vIghro'", :color=>"yolo"}
```

**Comment by neonichu** [comment]
I think that way of using it also works. Personally, I think the `locale` parameter is good for having a scope in which you deal with just one language.

**Comment by pxlpnk** [comment]
The change would just allow the user to access all the fields. Also when they would change the name for example and save it again, the other fields would be removed as they are not included in the request.
So it actually fixes a bug.

**Comment by asymmetric** [comment]
@grncdr I'm actually quite happy with the way it works now - keeps the operation of changing locale isolated.

**Comment by grncdr** [comment]
Looks good to merge from my side.

**Pull request merged**
