### PR TITLE
Fix creation of entries with just an id

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by dlitvakb** [comment]
@neonichu can you add this change to #71 they are very related

**Comment by neonichu** [comment]
@dlitvakb let's get #71 merged first, see my comment

**Comment by neonichu** [comment]
Just the test is left now since #71 also resolved the issue itself, but still makes sense so that we don't break this either in the future :)

**Comment by dlitvakb** [comment]
@neonichu can you rebase and squash the commits onto a single one?

**Comment by neonichu** [comment]
Ah yeah, not sure how I ended up with the empty commit :monkey_face:

**Comment by neonichu** [comment]
@dlitvakb squashed now

**Pull request merged**
