### PR TITLE
Add deleted property to fields

### PR DESCRIPTION
**Pull request by seand7565**
This property allows you to mark fields for deletion

See: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type-activation

### CODE REVIEW

**Comment by rubydog** [comment]
Hi @seand7565, thanks for the PR. Can you please add a test case for the proposed code changes?

Cheers

**Comment by ghepting** [comment]
Hey @seand7565 – did you want to add test case(s) for this so we can get this improvement added as @rubydog suggested?

**Comment by seand7565** [comment]
@rubydog @ghepting Added!

**Comment by rubydog** [comment]
Duplicate #258

**Pull request closed without merging**
