### PR TITLE
Adds getter/setter for EditorInterface#sidebar property

### LINKED ISSUE #229: editor_interface missing sidebar implementation
Hello! It appears that contentful-management.rb is missing the implementation to manage the sidebar configurations on a `Contentful::Management::EditorInterface` resource, which is critical for some of the work our team at Square is working on

Reference: https://www.contentful.com/developers/docs/extensibility/custom-sidebar/ 
API Reference: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/editor-interface 

Ruby SDK missing `.sidebar` getter/setters. Upon inspection of the `raw_object` the API response is correct, but the ruby SDK is missing this piece.

Opening an enterprise support ticket referencing this github issue. In the meantime, do you recommend modifying the raw_object manually and saving, or is there a better workflow within the constraints of the current implementation?

image

### PR DESCRIPTION
**Pull request by rubydog**
Fixes #229

### CODE REVIEW

**Review by ruderngespra — APPROVED** [review]

**Comment by ghepting** [comment]
Have you verified that this doesn't leave the Content Type in an unsaved state? I did this manually on a branch on my fork and couldn't figure out how to get save/publish to actually not leave the content types in this "unsaved" state

**Comment by rubydog** [comment]
@ghepting yes, I verified and the content type is not in unsaved state. You can follow the examples in spec https://github.com/contentful/contentful-management.rb/pull/231/files?file-filters%5B%5D=.rb#diff-6774af1da49f7efc6457ffdcd2a43f07bf2598a4a06b7e03c2f07d67f4e15ac4

**Comment by ghepting** [comment]
Excellent thank you!

**Review by ghepting — APPROVED** [review]
LGTM, exactly what i had done spiking on this, too: https://github.com/ghepting/contentful-management.rb/pull/1/files

**Comment by dlitvakb** [comment]
Released as `3.3.0`

**Pull request merged**
