### PR TITLE
configure VCR to redact CMA tokens

### PR DESCRIPTION
**Pull request by ghepting**
@rubydog this will prevent contributors from accidentally committing their CMA tokens in VCR cassettes

reference: https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/filter-sensitive-data

### CODE REVIEW

**Review by rubydog — APPROVED** [review]

**Comment by rubydog** [comment]
This is good. Thanks!

**Comment by ghepting** [comment]
Updated this to not fail specs when there is no head (see conditional in filter_sensitive_data evaluation block)

**Comment by rubydog** [comment]
@ghepting Can you please fix the conflicts so this can go in master as well.

Cheers

**Comment by ghepting** [comment]
> @ghepting Can you please fix the conflicts so this can go in master as well.
> 
> Cheers

Yep, will do when I'm at my desk

**Comment by ghepting** [comment]
> > @ghepting Can you please fix the conflicts so this can go in master as well.
> > Cheers
> 
> Yep, will do when I'm at my desk

All set @rubydog – I added the changelog note to Master to be included in the next release

**Pull request merged**
